{"timestamp":"2025-10-24T14:19:10.959593Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-24T14:19:10.972588Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/coresentiment_V2.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-24T14:19:15.956510Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:15.989205Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:16.022028Z","level":"info","event":"Current task name:send_notification","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:16.041578Z","level":"info","event":"Dag name:core-sentiment-V2","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:17.452785Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"gaierror","exc_value":"[Errno -5] No address associated with hostname","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/smtp/operators/smtp.py","lineno":89,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/smtp/hooks/smtp.py","lineno":79,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/smtp/hooks/smtp.py","lineno":101,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/smtp/hooks/smtp.py","lineno":152,"name":"_build_client"},{"filename":"/usr/python/lib/python3.12/smtplib.py","lineno":1022,"name":"__init__"},{"filename":"/usr/python/lib/python3.12/smtplib.py","lineno":255,"name":"__init__"},{"filename":"/usr/python/lib/python3.12/smtplib.py","lineno":341,"name":"connect"},{"filename":"/usr/python/lib/python3.12/smtplib.py","lineno":1028,"name":"_get_socket"},{"filename":"/usr/python/lib/python3.12/smtplib.py","lineno":312,"name":"_get_socket"},{"filename":"/usr/python/lib/python3.12/socket.py","lineno":841,"name":"create_connection"},{"filename":"/usr/python/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-24T14:19:17.477054Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:17.491954Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:17.507900Z","level":"info","event":"Task:<Task(EmailOperator): send_notification>","logger":"task.stdout"}
{"timestamp":"2025-10-24T14:19:17.524574Z","level":"info","event":"Failure caused by [Errno -5] No address associated with hostname","logger":"task.stdout"}
